- 인코딩:
- 원핫 인코딩의 예인가..
- 만약 데이터가 성별: 여자 여자 남자 남자 여자 이렇게 있으면
- 여자: 1 1 1 0 0 1
- 남자: 0 0 0 1 1 0
- 이렇게 2개의 컬럼으로 나뉨
- 2개 외에도 n개 값이 있으면 n개의 컬럼으로 나눠지는듯

In [2]:
# OneHotEncoder ##############################################################################
import numpy as np
import pandas as pd

from sklearn.preprocessing import OneHotEncoder
df = pd.DataFrame([
    [2,1,'male','A',3],
    [3,2,'female','C',5],
    [3,4,'male','B',7],
    [5,5,'female','A',10],
    [7,5,'female','B',12],
    [2,5,'male','A',7],
    [9,2,'male','C',13]
], columns=['hours', 'attendance', 'sex', 'cate', 'score'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   hours       7 non-null      int64 
 1   attendance  7 non-null      int64 
 2   sex         7 non-null      object
 3   cate        7 non-null      object
 4   score       7 non-null      int64 
dtypes: int64(3), object(2)
memory usage: 408.0+ bytes


In [5]:
df

hours  attendance     sex cate  score
0      2           1    male    A      3
1      3           2  female    C      5
2      3           4    male    B      7
3      5           5  female    A     10
4      7           5  female    B     12
5      2           5    male    A      7
6      9           2    male    C     13

In [3]:
ohe = OneHotEncoder(sparse=False)
ohe.fit(df[['sex']]) # Series encoding
encoding1=ohe.transform(df[['sex']]) # array of float64
print(ohe.transform(df[['sex']]))
# 결과가 2차열 배열이 됨

[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]]


In [6]:
# 시리즈를 fit
array1=np.array(df[['sex']]) 
ohe = OneHotEncoder(sparse=False)
ohe.fit(array1) # array encoding
encoding1=ohe.transform(df[['sex']]) # array of float64
print(ohe.transform(df[['sex']]))

[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]]


/Users/min0/Downloads/anaconda3/lib/python3.9/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but OneHotEncoder was fitted without feature names
  warnings.warn(
/Users/min0/Downloads/anaconda3/lib/python3.9/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but OneHotEncoder was fitted without feature names
  warnings.warn(


In [7]:
# df 전체를 fit > 오류남
ohe = OneHotEncoder(sparse=False)
ohe.fit(df) # dataframe encoding
encoding1=ohe.transform(df) # array of float64; dir(ohe); ohe.categories_; help(ohe.fit)
print(ohe.transform(df[['sex']]))

/Users/min0/Downloads/anaconda3/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names seen at fit time, yet now missing:
- attendance
- cate
- hours
- score

  warnings.warn(message, FutureWarning)


ValueError: X has 1 features, but OneHotEncoder is expecting 5 features as input.

In [8]:
# cate는 속성이 ABC 3개니까...
ohe.fit(df[['cate']])
cateencodeing=ohe.transform(df[['cate']])
print(ohe.transform(df[['cate']]))

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [9]:
df = pd.DataFrame([
    [2,1,'A',3],
    [3,2,'C',5],
    [3,4,'B',7],
    [5,5,'A',10],
    [7,5,'B',12],
    [2,5,'A',7],
    [9,2,'C',13]
], columns=['hours', 'attendance', 'cate', 'score'])

In [10]:
df

hours  attendance cate  score
0      2           1    A      3
1      3           2    C      5
2      3           4    B      7
3      5           5    A     10
4      7           5    B     12
5      2           5    A      7
6      9           2    C     13

In [11]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
ohe.fit(df[['cate']])
print(ohe.transform(df[['cate']]))

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [13]:
# 위 결과를 데이터 프레임으로 변경
df_cate = pd.DataFrame(ohe.transform(df[['cate']]), columns=['cate0', 'cate1', 'cate2'])
df_cate

cate0  cate1  cate2
0    1.0    0.0    0.0
1    0.0    0.0    1.0
2    0.0    1.0    0.0
3    1.0    0.0    0.0
4    0.0    1.0    0.0
5    1.0    0.0    0.0
6    0.0    0.0    1.0

In [14]:
# cate 3개의 값을 따로ㄷ따로 원핫인코딩 한 거 합쳐서 만들기.
# 이렇게 했을 때 정확도 높아질 수도 있다...
df = pd.concat([df[['hours', 'attendance']], df_cate, df[['score']]], axis=1)
df

hours  attendance  cate0  cate1  cate2  score
0      2           1    1.0    0.0    0.0      3
1      3           2    0.0    0.0    1.0      5
2      3           4    0.0    1.0    0.0      7
3      5           5    1.0    0.0    0.0     10
4      7           5    0.0    1.0    0.0     12
5      2           5    1.0    0.0    0.0      7
6      9           2    0.0    0.0    1.0     13

In [15]:
x_data = df[['hours', 'attendance', 'cate0', 'cate1', 'cate2']]
y_data = df['score']
print(x_data)
print(y_data)

   hours  attendance  cate0  cate1  cate2
0      2           1    1.0    0.0    0.0
1      3           2    0.0    0.0    1.0
2      3           4    0.0    1.0    0.0
3      5           5    1.0    0.0    0.0
4      7           5    0.0    1.0    0.0
5      2           5    1.0    0.0    0.0
6      9           2    0.0    0.0    1.0
0     3
1     5
2     7
3    10
4    12
5     7
6    13
Name: score, dtype: int64


In [16]:
# LabelEncoder ##############################################################################
# + replace도 이거랑 비슷
# 아깐 하나의 값을 3개로 나눴다면 이번엔 여러 값을 하나로 묶는 것....???(?)
import pandas as pd
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit([1, 2, 2, 6])

LabelEncoder()

In [17]:
#LabelEncoder()
le.classes_
# array([1, 2, 6])
le.transform([1, 1, 2, 6])
# array([0, 0, 1, 2]...)
le.inverse_transform([0, 0, 1, 2])
# array([1, 1, 2, 6])

array([1, 1, 2, 6])

In [18]:

# non-numerical labels (as long as they are hashable and comparable) to numerical labels.
le = preprocessing.LabelEncoder()
le.fit(["paris", "paris", "tokyo", "amsterdam"])
#LabelEncoder()
list(le.classes_)
# ['amsterdam', 'paris', 'tokyo']
le.transform(["tokyo", "tokyo", "paris"])
# array([2, 2, 1]...)
list(le.inverse_transform([2, 2, 1]))
# ['tokyo', 'tokyo', 'paris']

# 아까는 dp 전체 인코딩했을 때 에러났지만 이거는 된다. 더 강력함...

['tokyo', 'tokyo', 'paris']

In [19]:

###############################################################################
import pandas as pd
import numpy as np
s = pd.Series(list('abca'))
ss=pd.get_dummies(s)

s1 = ['a', 'b', np.nan]
ss1=pd.get_dummies(s1)
ss2=pd.get_dummies(s1, dummy_na=True)
df = pd.DataFrame({'A': ['a', 'b', 'a'], 'B': ['b', 'a', 'c'],'C': [1, 2, 3]})
ss3=pd.get_dummies(df, prefix=['col1', 'col2'])
ss4=pd.get_dummies(pd.Series(list('abcaa')))
ss5=pd.get_dummies(pd.Series(list('abcaa')), drop_first=True)
ss6=pd.get_dummies(pd.Series(list('abc')), dtype=float)

p1=pd.DataFrame(['a', 'b', np.nan])
pp1=pd.get_dummies(p1)

In [23]:
df

A  B  C
0  a  b  1
1  b  a  2
2  a  c  3

In [22]:
pp1

0_a    0_b
0   True  False
1  False   True
2  False  False